server:
  port: 8080

spring:
  #  事务的配置
  aop:
    proxy-target-class: true
  #    数据库配置
  datasource:
    url: jdbc:mysql://101.37.253.142:7896/logistics
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

  # json配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false
  servlet:
    multipart:
      max-file-size: 1024MB

  #  redis配置
  redis:
    port: 6565
    host: 101.37.253.142
    database: 0
  output:
    ansi:
      enabled: always
  #rabbitmq配置
  rabbitmq:
    host: 101.37.253.142
    port: 5672
    username: admin
    password: admin
    listener:
      simple:
        concurrency: 10
        max-concurrency: 20
      direct:
        prefetch: 5
    virtual-host: my_vhost
    # 默认的一个交换机 和队列名称
    template:
      exchange: direct_ttl_exchange
      routing-key: ttl
#mybatis配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    jdbc-type-for-null: varchar
  global-config:
    db-config:
      logic-not-delete-value: 1
      logic-delete-value: 0
  mapper-locations: classpath*:mapper/**/*Mapper.xml
#  日志配置
logging:
  config: classpath:loggin.xml


# 文件上传的地址
### 如下配置不懂的可以通过github私聊我
filePath:
  path: ~~~~~  #这里是本地路径
  osspath: 阿里云oss对象访问的低画质#######
#阿里云配置
aliyun:
  #OSS的配置
  END_POINT: ~~~~~~
  ACCESS_KEY_ID: ~~~~~~~
  ACCESS_KEY_SECRET: ~~~~~~
  BUKKET_NAME: ~~~~~~


  # 支付宝的配置
  PUBLIC_KEY: ~~~~~~~
  MER_PRIVATE_KEY: ~~~~+~~~~~
  APP_ID: ~~~~~
  ALIURL: ~~~~~~

  #实名认证token
  Authorization: ~~~~~~
  #实名认证的url
  AuthUrl: ~~~~~~


# 下面是腾讯云的配置
tenxun:
  #短信sdkid
  SDK_AppID: xxxxxxx
  #短信APPKEY
  APP_KEY: xxxxxxxxxx
  #短信模板id
  Template_ID: xxxxx
  #通用配置id
  SecrityId: xxxxxx
  #通用key
  SecrityKey: xxxxx
  #APP ID 短信的APPID
  APP_ID: xxxxxx


# 加密盐
securitySalt: $1$myxiaowang

Scheduled:
  message: 0 0 0/1 * * ? *